//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApplication
{
    using System;
    
    public partial class GetParticipantSessions_Result1
    {
        public int SessionId { get; set; }
        public int SessionGroupSessionGroupId { get; set; }
        public int ActivityActivityId { get; set; }
    }
}
